### ISSUE TITLE
Bug nachdem eine korrekte Eingabe nach einer falschen Eingabe getätigt wurde

### ISSUE THREAD

**Issue by chrissiwaffler** [CodingLegend27/MADN#3]
Ausgangssituation
----
Das Programm wartet auf eine Eingabe einer Nummer der Spielfigur eines Spielers.
_Hier in diesem Fall ist nur die Eingabe der Nummer 1 zulässig, da sich nur eine Figur auf dem Spielfeld befindet._

"1. Schritt"
----
Der Benutzer gibt eine falsche Nummer für die Figur ein.
_Hier in diesem Fall ist es z.B. die Nummer 3._

--> Das Programm reagiert korrekt auf die Eingabe und gibt aus, das die Eingabe der Nummer 3 nicht zulässig ist, da sich nur eine Figur auf dem Spielfeld befindet.

"2. Schritt"
----
Der Benutzer gibt anschließen eine richtige, mögliche Nummer für die Spielfigur ein.
_Hier in diesem Beispiel ist es die Nummer 1._

"3. Schritt"
----
Das Programm gibt anschließend folgende Fehlermeldung aus:
`Exception in thread "main" java.lang.IndexOutOfBoundsException:
Index 2 out of bounds for length 1
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.get(ArrayList.java:458)
        at controller.CONTROLLER.main(CONTROLLER.java:107)
        at controller.CONTROLLER.main(CONTROLLER.java:152)`

**Comment by chrissiwaffler** [comment]
Bug gefixt.
Issue wird geschlossen.
