### ISSUE TITLE
Bug Indexing der Felder

### ISSUE THREAD

**Issue by chrissiwaffler** [CodingLegend27/MADN#5]
Blaue Figur hat folgende Fehlermeldung bei einer korrekt eingegebenen Eingabe ausgelöst:
`Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 41 out of bounds for length 40
        at model.Model.schickeFigureWeiter(Model.java:198)
        at controller.CONTROLLER.main(CONTROLLER.java:109)
        at controller.CONTROLLER.main(CONTROLLER.java:152)`

**Comment by chrissiwaffler** [comment]
Bug wurde behoben.
